
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

workspace 'KDIntroView'

xcodeproj 'KDIntroView'
#xcodeproj 'ThriftProtocol/ThriftProtocol'

use_frameworks!

target 'KDIntroView_Example', :exclusive => true do
    pod 'KDIntroView', :git => 'https://github.com/likedan/KDIntroView.git'
end

target 'KDIntroView_Tests', :exclusive => true do
    pod 'KDIntroView', :git => 'https://github.com/likedan/KDIntroView.git'
    
end