source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KDIntroView_Example', :exclusive => true do
  pod "KDIntroView", :path => "../"
end

target 'KDIntroView_Tests', :exclusive => true do
  pod "KDIntroView", :path => "../"

  
end
