# Uncomment this line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

workspace 'IntroViewDemo'

xcodeproj 'IntroViewDemo'

use_frameworks!

target 'IntroViewDemo' do
    xcodeproj 'IntroViewDemo'
    
    pod 'KDIntroView', :git => '../../'
end

